### ISSUE TITLE
[RFE] Support for programming language package managers

### ISSUE THREAD

**Issue by msehnout** [dgoodwin/tito#237]
It would be nice, if `tito` could cooperate with a package manager specific to a certain programming language.

For example these package managers: [Cargo](http://doc.crates.io/manifest.html), [OPAM](https://opam.ocaml.org/doc/Packaging.html#Thequotopamquotfile), [Cabal](https://wiki.haskell.org/How_to_write_a_Haskell_program#Add_a_build_system) have their own configuration file with a line specifying the **version** of the package. `tito tag` could either read the version from the file or write to the file.

**Current solution:**
Using the template_file option, I can create something like this: 
tito.props:
```ini
[version_template]
destination_file = Cargo.toml
template_file = Cargo.toml.template
```
Template:
```toml
[package]
name = "hello_tito"
version = "$version"
authors = ["xxx"]

[dependencies]
```
Result:
```toml
[package]
name = "hello_tito"
version = "0.1.1"
authors = ["xxx"]

[dependencies]
```

But this is somewhat annoying when I want to change the `Cargo.toml` file without making new tag.

**Proposed solution:**
tito.props
```ini
[version_file]
pkg_type = cargo
config_file = Cargo.toml
```

What do you think? Is it a desirable feature in `tito`?
